ALTER TABLE "departments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "hospital_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "operating_rooms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "or_block_overrides" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "or_blocks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "patient_consents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "patients" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "admissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "appointments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "beds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "discharge_summaries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "medical_records" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "rooms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "vitals_flowsheet" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "waiting_list" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "housekeeping_tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "medications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prescriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "stock_transactions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "critical_value_alerts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lab_orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lab_tests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radiology_orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "radiology_reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "insurance_claims" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "online_payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payment_reminders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "anesthesia_records" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "surgical_cases" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "surgical_checklist_templates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "surgical_checklists" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ai_audit_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "data_retention_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "data_retention_policies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sent_reminders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "med_archiving_idx" ON "medical_records" USING btree ("hospital_id","is_archived","created_at");--> statement-breakpoint
CREATE INDEX "inv_archiving_idx" ON "invoices" USING btree ("hospital_id","is_archived","created_at");